### ISSUE TITLE
Reusable acceptance tests

### ISSUE THREAD

**Issue by 256dpi** [mqttjs/mqtt-stack#3]
It would be very cool to have reusable acceptance tests That way everyone can easily test his implementation and make sure that it works according to the OASIS specs.

**Comment by mcollina** [comment]
I think that is a perfect idea. A good chunk of stuff is already done inside mosca, and we can leverage it to build such an acceptance test tool.

The top thing would be to be able to even test mosquitto.

However, there is an MQTT interop test somewhere on the net, and I think that is written in Python.

**Comment by 256dpi** [comment]
Yes, they also have a spreadsheet that outlines all the needed tests: http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt.testing.git/tree/interoperability/MQTT%20Tests.ods

**Comment by 256dpi** [comment]
I added an editable version of all the tests that are due:
https://github.com/mqttjs/mqtt-stack/blob/master/test/acceptance/index.md.

@mcollina: Do you think we should cover each entry?

**Comment by mcollina** [comment]
Unfortunately I think so. We can do it in a separate project, so it is decoupled and reusable! Also, we should emit TAP format, so we might even build a nice 'compatibility website' kind of thing.

**Comment by 256dpi** [comment]
I started to integrate the mosca tests. We can afterwards put them in a 'mqtt-spec' repository or similar.

**Comment by mcollina** [comment]
Yeah, I think moving them to `mqtt-spec` makes a complete sense. Do you need a repo?

**Comment by 256dpi** [comment]
Ok, I would be ready to spin off the tests. Could you create the repo?

**Comment by mcollina** [comment]
Here you go https://github.com/mqttjs/mqtt-spec
