### ISSUE TITLE
Adapters

### ISSUE THREAD

**Issue by 256dpi** [mqttjs/mqtt-stack#4]
Right now the middlewares communicate through callbacks and event emitting with higher level application code:

``` js
var stack = require('mqtt-stack');

stack.use(new stack.InboundManager({
  relayMessage: function(ctx, callback) {
    // relay message using redis, amqp, ... to other clients
  }
}));
```

As every implementation will use a "Store" and "Broker" at some point, special middlewares could enable this functionality in an extendable way:

``` js
var stack = require('mqtt-stack');
var redis = require('mqtt-stack-redis')
var amqp = require('mqtt-stack-amqp');

var stack = new stack.Stack();

// Adapters register functions like 'storeMessage' and
// 'relayMessage' in an internal registry
stack.use(new redis.Store());
stack.use(new amqp.Broker));

// Falls back to the functions provided by the adapters
stack.use(new stack.InboundManager());
```

The 'Store' middleware:

``` js
var Store = function(){}

Store.prototype.storeMessage = function(ctx, calback){
  // handle the store request
};
```

The 'InboundManager' middleware:

``` js
var InboundManager = function(config){
  this.config = config;
};

InboundManager.prototype.storeMessage = function(ctx, callback){
  this.config.storeMessage(ctx, callback);
};

InboundManager.prototype.handle = function(client, packet) {
  // at some point
  this.stack.execute('storeMessage', {
    client: client,
    packet: packet
  }, function(results){
    // there are multiple results
  });
};
```

This system could be even used for the internal events like 'uncleanDisconnect' and etc.

**Comment by mcollina** [comment]
It's not exactly how these whole adapters work, I can use Redis for pubsub and message storage, or only storage and use Rabbit for the rest.

**Comment by 256dpi** [comment]
I updated the idea and examples above to make it more clear.

**Comment by mcollina** [comment]
It is still not clear to me what a 'broadcast' is in this context, also 'synchronization' is definitely not the right word. maybe `amqp.Broker`?.

**Comment by 256dpi** [comment]
Right now we have two middlewares to manage 'publish' messages. The ForwardManager publishes to the client while the BroadcastManager manages incoming messages. If you have better naming ideas, feel free to share. ;)

**Comment by mcollina** [comment]
How about calling them `InboundManager` and `OutboundManager`?

**Comment by 256dpi** [comment]
That definitely sounds better.

**Comment by 256dpi** [comment]
This is implemented! An example adapter can be found at: https://github.com/mqttjs/mqtt-stack/blob/master/test/support/memory_backend.js.
