### ISSUE TITLE
Move to mqtt-packet

### ISSUE THREAD

**Issue by mcollina** [mqttjs/mqtt-stack#6]
I think this should move from being mqtt-connection centered to just use mqtt-packet.
It is way faster, and it would be even faster in the short future.

**Comment by kokeksibir** [comment]
mqtt-stack is already using mqtt-packet, its mqtt-connection dependency is due to mqtt-spec.

**Comment by mcollina** [comment]
mqtt-connection is way slower than mqtt-packet, that was the point.
Il giorno lun 19 ott 2015 alle 10:24 Kamil Sulubulut <
notifications@github.com> ha scritto:

**Comment by kokeksibir** [comment]
OK, it's my bad, Client needs to be updated to take advantage of mqtt-packet update.

**Comment by kokeksibir** [comment]
@mcollina when I try to upgrade to mqtt-packet mqtt spec tests fail at "should relay and forward QoS 1 message" test. Do you have any idea what could be the thing I miss?

Another thing is, in the previous implementation stream.write function was providing callback on completion. In writeToStream there is not such possibility, how can we detect that write is uncorked, do you have any advise? 

If you'd like to take a look, please check https://github.com/kokeksibir/mqtt-stack

**Comment by mcollina** [comment]
I have no idea about the failing test. Regarding yhe callback: the data
will be passed to C++ after nextTick.

Why do you need that callback? The performant way for doing it will be to
call the callback (possibly with setImmediate) if writeToStream returns
true, and wait for the 'drain' event on the stream if not.
Il giorno sab 28 nov 2015 alle 16:48 Kamil Sulubulut <
notifications@github.com> ha scritto:

**Comment by kokeksibir** [comment]
Done with merge #7
